theme                    : jekyll-theme-cayman
url                      : "https://selosele.github.io/KLIC-markup-guide/index.html"
baseurl                  :
repository               : "selosele/KLIC-markup-guide"
lang                     : "ko"